---
- name: Restart network service
  service:
    name: network
    state: restarted
  listen: "restart network service"

- name: Clean up unused key pairs
  amazon.aws.ec2_key:
    name: "{{ key_name }}"
    state: absent
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    region: "{{ region }}"
  listen: "cleanup key pairs"

- name: Revoke security group rules
  amazon.aws.ec2_security_group:
    name: "{{ sec_group }}"
    rules:
      - proto: tcp
        ports:
          - 22
          - 80
          - 443
        cidr_ip: 0.0.0.0/0
        state: revoke
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    region: "{{ region }}"
  listen: "revoke sec group rules"

- name: Restart network service
  service:
    name: network
    state: restarted
  listen: "restart network service"

- name: Clean up unused key pairs
  amazon.aws.ec2_key:
    name: "{{ key_name }}"
    state: absent
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    region: "{{ region }}"
  listen: "cleanup key pairs"

- name: Revoke security group rules
  amazon.aws.ec2_security_group:
    name: "{{ sec_group }}"
    rules:
      - proto: tcp
        ports:
          - 22
          - 80
          - 443
        cidr_ip: 0.0.0.0/0
        state: revoke
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    region: "{{ region }}"
  listen: "revoke sec group rules"
